CREATE SEQUENCE users_id_seq START 1 INCREMENT 1;
CREATE SEQUENCE user_profiles_id_seq START 1 INCREMENT 1;
CREATE SEQUENCE professional_status_id_seq START 1 INCREMENT 1;

CREATE SEQUENCE banks_id_seq START 1 INCREMENT 1;
CREATE SEQUENCE currencies_id_seq START 1 INCREMENT 1;
CREATE SEQUENCE accounts_id_seq START 1 INCREMENT 1;
CREATE SEQUENCE account_infos_id_seq START 1 INCREMENT 1;
CREATE SEQUENCE cash_reports_id_seq START 1 INCREMENT 1;
